apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-k8s-app
  labels:
    app: express-k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-k8s-app
  template:
    metadata:
      labels:
        app: express-k8s-app
    spec:
      containers:
        - name: express-k8s-app
          image: linikerdev/express-k8s-app
          ports:
            - containerPort: 3000
              name: http
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: express-svc
  labels:
    app: express-k8s-app
spec:
  selector:
    app: express-k8s-app
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: http
      nodePort: 30000
  type: NodePort